package com.ashokmart;

import com.ashokmart.dao.*; import com.ashokmart.dao.impl.*; import com.ashokmart.model.*; import com.ashokmart.service.impl.*; import com.ashokmart.util.*; import org.junit.jupiter.api.*; import java.math.BigDecimal; import java.sql.*; import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

class AdminManagementBackendTest {
 private DatabaseConnectionPool pool; private ProductDao products; private OrderDao orders; private AdminUserServiceImpl users; private AdminProductServiceImpl productService; private AdminOrderServiceImpl orderService;
 @BeforeEach void setUp() throws Exception { pool=new DatabaseConnectionPool(DatabaseConfig.forTesting("jdbc:h2:mem:admin15_"+UUID.randomUUID().toString().replace('-','_'))); DatabaseInitializer.initialize(pool); seed(); UserDao ud=new UserDaoImpl(pool); products=new ProductDaoImpl(pool); orders=new OrderDaoImpl(pool); users=new AdminUserServiceImpl(ud,products,orders); productService=new AdminProductServiceImpl(products,ud); orderService=new AdminOrderServiceImpl(orders,ud); }
 @AfterEach void tearDown(){pool.close();}
 @Test void productFiltersPaginationAndStatusAreAdminScoped() throws Exception { AdminProductPage page=productService.getProducts(1,new AdminProductQuery("phone",null,null,true,1,1)); assertEquals(1,page.getTotalResults()); assertEquals("Phone",page.getProducts().get(0).getName()); assertTrue(productService.getProduct(1,2).isPresent()); productService.setStatus(1,2,false); assertFalse(products.findById(2).orElseThrow().isActive()); assertThrows(RuntimeException.class,()->productService.getProducts(3,new AdminProductQuery(null,null,null,null,1,10))); }
 @Test void ordersUsePersistedTotalsAndHistoricalUnitPrices() { AdminOrderPage page=orderService.getOrders(1,new AdminOrderModels.Query("buyer",null,1,10)); assertEquals(1,page.getTotalResults()); assertEquals(new BigDecimal("39.98"),page.getOrders().get(0).getTotalAmount()); var details=orderService.getOrder(1,1).orElseThrow(); assertEquals(new BigDecimal("19.99"),details.getItems().get(0).getUnitPrice()); assertEquals("Phone",details.getItems().get(0).getProductName()); assertEquals("Seller",details.getItems().get(0).getSellerName()); }
 @Test void dashboardAggregatesComeFromDatabase() { AdminStatistics s=users.getStatistics(1); assertEquals(3,s.getTotalUsers()); assertEquals(2,s.getTotalProducts()); assertEquals(2,s.getActiveProducts()); assertEquals(1,s.getInStockProducts()); assertEquals(1,s.getOutOfStockProducts()); assertEquals(1,s.getTotalOrders()); assertEquals(new BigDecimal("39.98"),s.getTotalRevenue()); assertEquals(new BigDecimal("39.98"),s.getAverageOrderValue()); }
 private void seed() throws Exception { try(Connection c=pool.getConnection()){exec(c,"INSERT INTO users(id,name,email,password_hash,role,enabled) VALUES(1,'Admin','admin@test','hash','ADMIN',TRUE)");exec(c,"INSERT INTO users(id,name,email,password_hash,role,enabled) VALUES(2,'Seller','seller@test','hash','SELLER',TRUE)");exec(c,"INSERT INTO users(id,name,email,password_hash,role,enabled) VALUES(3,'Buyer','buyer@test','hash','BUYER',TRUE)");exec(c,"INSERT INTO categories(id,name,description) VALUES(1,'Electronics','Devices')");exec(c,"INSERT INTO products(id,seller_id,category_id,name,description,price,stock_quantity,enabled) VALUES(1,2,1,'Phone','Smart phone',29.99,4,TRUE)");exec(c,"INSERT INTO products(id,seller_id,category_id,name,description,price,stock_quantity,enabled) VALUES(2,2,1,'Old Phone','Phone accessory',10.00,0,TRUE)");exec(c,"INSERT INTO orders(id,buyer_id,total_amount,status) VALUES(1,3,39.98,'PENDING')");exec(c,"INSERT INTO order_items(id,order_id,product_id,seller_id,quantity,unit_price,subtotal) VALUES(1,1,1,2,2,19.99,39.98)");}}
 private void exec(Connection c,String sql)throws Exception{try(PreparedStatement s=c.prepareStatement(sql)){s.executeUpdate();}}
}
