package com.ashokmart;
import com.ashokmart.dao.*; import com.ashokmart.dao.impl.*; import com.ashokmart.model.*; import com.ashokmart.service.*; import com.ashokmart.service.impl.*; import com.ashokmart.util.*; import org.junit.jupiter.api.*; import java.math.*; import java.sql.*; import java.util.*; import static org.junit.jupiter.api.Assertions.*;
class ReviewBackendTest { private DatabaseConnectionPool pool; private ReviewDao dao; private ReviewService service;
 @BeforeEach void setUp()throws Exception{pool=new DatabaseConnectionPool(DatabaseConfig.forTesting("jdbc:h2:mem:reviews_"+UUID.randomUUID().toString().replace('-','_')));DatabaseInitializer.initialize(pool);seed();dao=new ReviewDaoImpl(pool);service=new ReviewServiceImpl(dao,new ProductDaoImpl(pool));}
 @AfterEach void tearDown(){pool.close();}
 @Test void createListAverageAndCountUseDatabase(){long id=service.createReview(1,1,5,"Excellent product");assertTrue(id>0);assertEquals(1,service.getReviewCount(1));assertEquals(new BigDecimal("5.0"),service.getAverageRating(1));assertEquals("Buyer One",service.getProductReviews(1).get(0).getBuyerName());}
 @Test void purchaseEligibilityAndDuplicateAreServerEnforced(){assertTrue(service.canReview(1,1));service.createReview(1,1,4,"Good");assertFalse(service.canReview(1,1));assertThrows(ReviewException.class,()->service.createReview(1,1,5,"Again"));assertFalse(service.canReview(2,1));assertThrows(ReviewException.class,()->service.createReview(2,1,5,"Not purchased"));}
 @Test void invalidRatingAndOwnershipAreRejected(){assertThrows(ReviewException.class,()->service.createReview(1,1,0,"bad"));long id=service.createReview(1,1,5,"Great");assertThrows(ReviewException.class,()->service.updateReview(2,id,1,"hijack"));assertThrows(ReviewException.class,()->service.deleteReview(2,id));service.updateReview(1,id,3,"Updated");assertEquals(3,service.getReview(id).orElseThrow().getRating());service.deleteReview(1,id);assertTrue(service.getReview(id).isEmpty());}
 @Test void daoSupportsDirectOperationsAndHistoricalReviewerData()throws Exception{long id=dao.create(new Review(0,1,1,2,"Okay",null,null));assertTrue(dao.findById(id).isPresent());assertTrue(dao.findByBuyerAndProduct(1,1).isPresent());assertEquals(1,dao.countByProductId(1));assertTrue(dao.update(new Review(id,1,1,4,"Better",null,null),1));assertTrue(dao.delete(id,1));}
 private void seed()throws Exception{try(Connection c=pool.getConnection()){exec(c,"INSERT INTO users(id,name,email,password_hash,role) VALUES(1,'Buyer One','buyer1@test','hash','BUYER')");exec(c,"INSERT INTO users(id,name,email,password_hash,role) VALUES(2,'Buyer Two','buyer2@test','hash','BUYER')");exec(c,"INSERT INTO users(id,name,email,password_hash,role) VALUES(3,'Seller','seller@test','hash','SELLER')");exec(c,"INSERT INTO categories(id,name) VALUES(1,'General')");exec(c,"INSERT INTO products(id,seller_id,category_id,name,price,stock_quantity,enabled) VALUES(1,3,1,'Phone',10.00,3,TRUE)");exec(c,"INSERT INTO orders(id,buyer_id,total_amount,status) VALUES(1,1,10.00,'DELIVERED')");exec(c,"INSERT INTO order_items(id,order_id,product_id,seller_id,quantity,unit_price,subtotal) VALUES(1,1,1,3,1,10.00,10.00)");}}
 private void exec(Connection c,String sql)throws Exception{try(PreparedStatement s=c.prepareStatement(sql)){s.executeUpdate();}}
}
