package com.ashokmart.dao.impl;
import com.ashokmart.dao.ReviewDao; import com.ashokmart.model.Review; import com.ashokmart.util.DatabaseConnectionPool; import java.math.*; import java.sql.*; import java.util.*;
public final class ReviewDaoImpl implements ReviewDao { private final DatabaseConnectionPool pool; public ReviewDaoImpl(DatabaseConnectionPool pool){this.pool=pool;}
 private static final String C="r.id,r.product_id,r.buyer_id,r.rating,r.comment,r.created_at,r.updated_at,u.name AS buyer_name";
 public List<Review> findByProductId(long productId)throws SQLException{String sql="SELECT "+C+" FROM reviews r JOIN users u ON u.id=r.buyer_id WHERE r.product_id=? ORDER BY r.created_at DESC,r.id DESC";try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,productId);try(ResultSet r=s.executeQuery()){List<Review> out=new ArrayList<>();while(r.next())out.add(map(r));return out;}}}
 public Optional<Review> findById(long id)throws SQLException{return queryOne("SELECT "+C+" FROM reviews r JOIN users u ON u.id=r.buyer_id WHERE r.id=?",id);}
 public Optional<Review> findByBuyerAndProduct(long buyer,long product)throws SQLException{String sql="SELECT "+C+" FROM reviews r JOIN users u ON u.id=r.buyer_id WHERE r.buyer_id=? AND r.product_id=?";try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,buyer);s.setLong(2,product);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}}
 public long create(Review review)throws SQLException{String sql="INSERT INTO reviews(product_id,buyer_id,rating,comment) VALUES(?,?,?,?)";try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){s.setLong(1,review.getProductId());s.setLong(2,review.getBuyerId());s.setInt(3,review.getRating());s.setString(4,review.getComment());s.executeUpdate();try(ResultSet k=s.getGeneratedKeys()){if(!k.next())throw new SQLException("Review ID unavailable");return k.getLong(1);}}}
 public boolean update(Review review,long buyerId)throws SQLException{String sql="UPDATE reviews SET rating=?,comment=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND buyer_id=?";try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setInt(1,review.getRating());s.setString(2,review.getComment());s.setLong(3,review.getId());s.setLong(4,buyerId);return s.executeUpdate()==1;}}
 public boolean delete(long id,long buyerId)throws SQLException{try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement("DELETE FROM reviews WHERE id=? AND buyer_id=?")){s.setLong(1,id);s.setLong(2,buyerId);return s.executeUpdate()==1;}}
 public long countByProductId(long productId)throws SQLException{return aggregate("SELECT COUNT(*) FROM reviews WHERE product_id=?",productId);}
 public BigDecimal averageRating(long productId)throws SQLException{try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement("SELECT AVG(rating) FROM reviews WHERE product_id=?")){s.setLong(1,productId);try(ResultSet r=s.executeQuery()){r.next();BigDecimal v=r.getBigDecimal(1);return v==null?BigDecimal.ZERO:v.setScale(1,RoundingMode.HALF_UP);}}}
 public boolean hasPurchasedProduct(long buyerId,long productId)throws SQLException{String sql="SELECT 1 FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.buyer_id=? AND oi.product_id=? AND o.status <> 'CANCELLED' LIMIT 1";try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,buyerId);s.setLong(2,productId);try(ResultSet r=s.executeQuery()){return r.next();}}}
 private Optional<Review> queryOne(String sql,long id)throws SQLException{try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}}
 private long aggregate(String sql,long id)throws SQLException{try(Connection c=pool.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);try(ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private Review map(ResultSet r)throws SQLException{return new Review(r.getLong("id"),r.getLong("product_id"),r.getLong("buyer_id"),r.getInt("rating"),r.getString("comment"),r.getTimestamp("created_at").toLocalDateTime(),r.getTimestamp("updated_at").toLocalDateTime(),r.getString("buyer_name"));}
}
