<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Seller Orders | AshokMart</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/auth.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/css/seller.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/css/seller-orders.css"></head>
<body><jsp:include page="/WEB-INF/views/includes/header.jsp" /><main class="seller-layout"><div class="seller-page-heading"><div><p class="eyebrow">Seller workspace</p><h1>Seller Orders</h1><p class="lede">Fulfill orders containing your products. Totals shown are your product subtotal, not the buyer's full order total.</p></div><div class="seller-heading-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/seller/dashboard">Dashboard</a><a class="secondary-button" href="${pageContext.request.contextPath}/seller/products">My Products</a></div></div>
<c:if test="${not empty sellerOrderSuccess}"><div class="form-message success">${sellerOrderSuccess}</div></c:if><c:if test="${not empty sellerOrderError}"><div class="form-message error">${sellerOrderError}</div></c:if>
<c:choose><c:when test="${empty orders}"><section class="seller-empty seller-panel"><p class="eyebrow">No fulfillment queue</p><h2>No relevant orders yet.</h2><p>When buyers purchase your products, the relevant orders will appear here.</p><a class="secondary-button" href="${pageContext.request.contextPath}/seller/products">Manage products</a></section></c:when><c:otherwise><section class="seller-order-list"><c:forEach items="${orders}" var="order"><article class="seller-order-card"><div class="seller-order-card-top"><div><span class="order-label">Order #${order.id}</span><h2>${order.createdAt}</h2></div><span class="order-status status-${fn:toLowerCase(order.status)}"><span class="status-dot"></span>${order.status}</span></div><div class="seller-order-meta"><span>${order.itemCount} relevant item<c:if test="${order.itemCount != 1}">s</c:if></span><strong><fmt:formatNumber value="${order.sellerSubtotal}" type="currency" currencyCode="USD" /></strong></div><div class="seller-order-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/seller/orders/view?id=${order.id}">View details</a><c:if test="${order.status == 'PENDING'}"><form method="post" action="${pageContext.request.contextPath}/seller/orders/status"><input type="hidden" name="orderId" value="${order.id}"><input type="hidden" name="status" value="CONFIRMED"><button class="primary-button seller-small-button" type="submit">Confirm order</button></form></c:if><c:if test="${order.status == 'CONFIRMED'}"><form method="post" action="${pageContext.request.contextPath}/seller/orders/status"><input type="hidden" name="orderId" value="${order.id}"><input type="hidden" name="status" value="PROCESSING"><button class="primary-button seller-small-button" type="submit">Start processing</button></form></c:if><c:if test="${order.status == 'PROCESSING'}"><form method="post" action="${pageContext.request.contextPath}/seller/orders/status"><input type="hidden" name="orderId" value="${order.id}"><input type="hidden" name="status" value="SHIPPED"><button class="primary-button seller-small-button" type="submit">Mark shipped</button></form></c:if><c:if test="${order.status == 'SHIPPED'}"><form method="post" action="${pageContext.request.contextPath}/seller/orders/status"><input type="hidden" name="orderId" value="${order.id}"><input type="hidden" name="status" value="DELIVERED"><button class="primary-button seller-small-button" type="submit">Mark delivered</button></form></c:if></div></article></c:forEach></section></c:otherwise></c:choose></main></body></html>
