package com.ashokmart.service.impl;
import com.ashokmart.dao.ReviewDao; import com.ashokmart.dao.ProductDao; import com.ashokmart.model.*; import com.ashokmart.service.*; import org.slf4j.*; import java.sql.SQLException; import java.util.*; import java.math.BigDecimal;
public final class ReviewServiceImpl implements ReviewService { private static final Logger LOG=LoggerFactory.getLogger(ReviewServiceImpl.class); private final ReviewDao reviews; private final ProductDao products;
 public ReviewServiceImpl(ReviewDao reviews,ProductDao products){this.reviews=reviews;this.products=products;}
 public List<Review> getProductReviews(long productId){requireId(productId,"product");try{return reviews.findByProductId(productId);}catch(SQLException e){LOG.error("Review lookup failed",e);throw new IllegalStateException("Reviews are temporarily unavailable.",e);}}
 public Optional<Review> getReview(long reviewId){requireId(reviewId,"review");try{return reviews.findById(reviewId);}catch(SQLException e){LOG.error("Review lookup failed",e);throw new IllegalStateException("Review is temporarily unavailable.",e);}}
 public Optional<Review> getBuyerReview(long buyerId,long productId){requireBuyer(buyerId);requireId(productId,"product");try{return reviews.findByBuyerAndProduct(buyerId,productId);}catch(SQLException e){LOG.error("Buyer review lookup failed",e);throw new IllegalStateException("Review is temporarily unavailable.",e);}}
 public BigDecimal getAverageRating(long productId){requireId(productId,"product");try{return reviews.averageRating(productId);}catch(SQLException e){LOG.error("Review average lookup failed",e);throw new IllegalStateException("Ratings are temporarily unavailable.",e);}}
 public long getReviewCount(long productId){requireId(productId,"product");try{return reviews.countByProductId(productId);}catch(SQLException e){LOG.error("Review count lookup failed",e);throw new IllegalStateException("Ratings are temporarily unavailable.",e);}}
 public boolean canReview(long buyerId,long productId){requireBuyer(buyerId);requireId(productId,"product");try{Product p=products.findById(productId).orElseThrow(()->new ReviewException("Product not found."));if(!p.isActive())return false;return reviews.hasPurchasedProduct(buyerId,productId)&&reviews.findByBuyerAndProduct(buyerId,productId).isEmpty();}catch(ReviewException e){throw e;}catch(SQLException e){LOG.error("Review eligibility lookup failed",e);throw new IllegalStateException("Review eligibility is temporarily unavailable.",e);}}
 public long createReview(long buyerId,long productId,int rating,String comment){requireBuyer(buyerId);validateRating(rating);String text=normalizeComment(comment);try{Product p=products.findById(productId).orElseThrow(()->new ReviewException("Product not found."));if(!p.isActive())throw new ReviewException("This product is no longer available for review.");if(!reviews.hasPurchasedProduct(buyerId,productId))throw new ReviewException("You can review products purchased through AshokMart.");if(reviews.findByBuyerAndProduct(buyerId,productId).isPresent())throw new ReviewException("You have already reviewed this product.");return reviews.create(new Review(0,productId,buyerId,rating,text,null,null));}catch(ReviewException e){throw e;}catch(SQLException e){if("23505".equals(e.getSQLState()))throw new ReviewException("You have already reviewed this product.");LOG.error("Review creation failed",e);throw new IllegalStateException("Review could not be saved.",e);}}
 public void updateReview(long buyerId,long reviewId,int rating,String comment){requireBuyer(buyerId);validateRating(rating);String text=normalizeComment(comment);try{Review old=reviews.findById(reviewId).orElseThrow(()->new ReviewException("Review not found."));if(old.getBuyerId()!=buyerId)throw new ReviewException("You may only edit your own review.");if(!reviews.update(new Review(reviewId,old.getProductId(),buyerId,rating,text,old.getCreatedAt(),old.getUpdatedAt()),buyerId))throw new ReviewException("Review not found.");}catch(ReviewException e){throw e;}catch(SQLException e){LOG.error("Review update failed",e);throw new IllegalStateException("Review could not be updated.",e);}}
 public void deleteReview(long buyerId,long reviewId){requireBuyer(buyerId);requireId(reviewId,"review");try{Review old=reviews.findById(reviewId).orElseThrow(()->new ReviewException("Review not found."));if(old.getBuyerId()!=buyerId)throw new ReviewException("You may only delete your own review.");if(!reviews.delete(reviewId,buyerId))throw new ReviewException("Review not found.");}catch(ReviewException e){throw e;}catch(SQLException e){LOG.error("Review deletion failed",e);throw new IllegalStateException("Review could not be deleted.",e);}}
 private String normalizeComment(String value){if(value==null||value.trim().isEmpty())return null;String t=value.trim();if(t.length()>4000)throw new ReviewException("Review text must be 4,000 characters or fewer.");return t;}
 private void validateRating(int rating){if(rating<1||rating>5)throw new ReviewException("Rating must be between 1 and 5.");} private void requireId(long id,String label){if(id<=0)throw new ReviewException("A valid "+label+" is required.");} private void requireBuyer(long id){if(id<=0)throw new ReviewException("You must be logged in as a buyer.");}
}
